name: fiurozz

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./configs/.env
    environment:
      CATALOG_SERVICE: http://catalog-service:8083
      OTEL_ENDPOINT: jaeger:4317
    volumes:
      - gateway-logs:/app/logs
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    depends_on:
      - catalog-service
      - jaeger
